##################################
# @Author : Ganesh Nagarajan
# Purpose:
# Create place holder metadata tables.
##################################
CREATE TABLE affiliations (AFF_ID STRING,AFF_NAME STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE authors (AUTH_ID STRING,AUTH_NAME STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE conference (CONF_ID STRING,SH_NAME STRING,FULL_NAME STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE conferenceinstance (CONF_ID STRING, CONF_INST_ID STRING,SH_NAME STRING,LOC STRING,OFF_URL STRING,CONF_STDATE STRING,CONF_EDATE STRING,CONF_ADATE STRING,CONF_SUBDATE STRING,CONF_SDATE STRING,CONF_NOTDATE STRING,CONF_FINDATE STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE fieldofstudy (FLD_ID STRING,F_NAME STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE journals (JRNL_ID STRING,J_NAME STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE papers (PPR_ID STRING,PPR_TITLE STRING,NORM_TITLE STRING,PPR_YEAR STRING,PPR_DATE STRING,PP_DOI STRING,VENUE_NAME STRING,NORM_VNUE STRING,JRNL_ID STRING,CONF_ID STRING,P_RANK BIGINT) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE paperaffiliations (PPR_ID STRING,AUTH_ID STRING,AFF_ID STRING,OR_AFF_NAME STRING,NORM_AFF_NAME STRING,SEQ_NM BIGINT) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE paperkeywords (PPR_ID STRING,KEY_NAME STRING,FOS_ID STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE paperreferences (PPR_ID STRING,PPR_REF_ID STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
CREATE TABLE paperurl (PPR_ID STRING, URL STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;
